spring:
  # H2 데이터베이스 설정 (테스트용 인메모리)
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
    username: sa
    password:
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
    generate-ddl: true

  # JWT 시크릿 키 (테스트용)
  jwt:
    secret: 66c22d185f45958d97fe02c81d0e5ed3fbae56ea3e1df3fc4ba6cefd3c9540361c147a6d43defddadb4238afb13989ae9f22640dc271b0f0425bdcd152ab3017

  # Redis 설정
  data:
    redis:
      host: 127.0.0.1
      port: 6379

  # 파일 업로드 설정
  servlet:
    multipart:
      enabled: true
      location: /Users/jeonjeonghyeon/bootPhoto
      max-request-size: 10MB
      max-file-size: 1MB

# 로깅 레벨 설정
logging:
  level:
    org:
      springframework:
        security: debug
      hibernate:
        type:
          descriptor:
            sql: trace
    #... (필요에 따라 다른 로깅 레벨 추가)

# 커스텀 프로퍼티
ticket:
  upload:
    path: /Users/jeonjeonghyeon/bootPhoto/uploads
  entry:
    secret: test-entry-secret
  sms:
    allow-test-code: true

management:
  health:
    redis:
      enabled: false
